#pragma line 1 "src/tdt.c" ::: -10
#pragma line 1 "src/tdt.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 300 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 2
#pragma line 7 "<command line>" 2 ::: 120
#pragma line 1 "<built-in>" 2 ::: 121
#pragma line 1 "src/tdt.c" 2 ::: 122
#pragma line 46 "src/tdt.c" ::: 123
#pragma line 1 "src/tdt.h" 1 ::: 124
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/ap_cint.h" 1 ::: 128
#pragma line 62 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/ap_cint.h" ::: 129
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 130
#pragma line 25 "/usr/include/string.h" 3 4 ::: 131
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 132
#pragma line 345 "/usr/include/features.h" 3 4 ::: 133
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 134
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 135
#pragma line 367 "/usr/include/features.h" 3 4 ::: 136
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 137
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 138
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 139
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 140
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 141
#pragma line 391 "/usr/include/features.h" 3 4 ::: 142
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 143
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 144
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 145
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 146
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 147
#pragma line 26 "/usr/include/string.h" 2 3 4 ::: 148
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 155
#pragma line 31 "/opt/Xilinx/Vivado/2018.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 156
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 167
#pragma line 42 "/usr/include/string.h" 3 4 ::: 168
#pragma line 92 "/usr/include/string.h" 3 4 ::: 194
#pragma line 125 "/usr/include/string.h" 3 4 ::: 197
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 233
#pragma line 27 "/usr/include/xlocale.h" 3 4 ::: 234
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 251
#pragma line 231 "/usr/include/string.h" 3 4 ::: 273
#pragma line 258 "/usr/include/string.h" 3 4 ::: 276
#pragma line 280 "/usr/include/string.h" 3 4 ::: 279
#pragma line 310 "/usr/include/string.h" 3 4 ::: 286
#pragma line 337 "/usr/include/string.h" 3 4 ::: 289
#pragma line 394 "/usr/include/string.h" 3 4 ::: 310
#pragma line 422 "/usr/include/string.h" 3 4 ::: 326
#pragma line 440 "/usr/include/string.h" 3 4 ::: 328
#pragma line 484 "/usr/include/string.h" 3 4 ::: 348
#pragma line 512 "/usr/include/string.h" 3 4 ::: 351
#pragma line 529 "/usr/include/string.h" 3 4 ::: 359
#pragma line 552 "/usr/include/string.h" 3 4 ::: 366
#pragma line 63 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/ap_cint.h" 2 ::: 390
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 391
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 392
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 393
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 394
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 396
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 397
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 398
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 399
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 426
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 427
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 428
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 497
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 511
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 513
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 514
#pragma line 31 "/usr/include/libio.h" 3 4 ::: 515
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 516
#pragma line 15 "/usr/include/_G_config.h" 3 4 ::: 517
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 518
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 519
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 524
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 525
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 539
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 550
#pragma line 49 "/usr/include/libio.h" 3 4 ::: 551
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 552
#pragma line 30 "/opt/Xilinx/Vivado/2018.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 553
#pragma line 48 "/opt/Xilinx/Vivado/2018.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 555
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 557
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 558
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 578
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 589
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 630
#pragma line 333 "/usr/include/libio.h" 3 4 ::: 660
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 682
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 686
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 701
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 713
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 719
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 721
#pragma line 164 "/usr/include/stdio.h" 3 4 ::: 731
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 732
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 733
#pragma line 195 "/usr/include/stdio.h" 3 4 ::: 756
#pragma line 209 "/usr/include/stdio.h" 3 4 ::: 758
#pragma line 227 "/usr/include/stdio.h" 3 4 ::: 766
#pragma line 237 "/usr/include/stdio.h" 3 4 ::: 769
#pragma line 252 "/usr/include/stdio.h" 3 4 ::: 776
#pragma line 272 "/usr/include/stdio.h" 3 4 ::: 778
#pragma line 306 "/usr/include/stdio.h" 3 4 ::: 788
#pragma line 319 "/usr/include/stdio.h" 3 4 ::: 790
#pragma line 356 "/usr/include/stdio.h" 3 4 ::: 820
#pragma line 412 "/usr/include/stdio.h" 3 4 ::: 858
#pragma line 425 "/usr/include/stdio.h" 3 4 ::: 864
#pragma line 443 "/usr/include/stdio.h" 3 4 ::: 875
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 882
#pragma line 494 "/usr/include/stdio.h" 3 4 ::: 898
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 912
#pragma line 550 "/usr/include/stdio.h" 3 4 ::: 921
#pragma line 561 "/usr/include/stdio.h" 3 4 ::: 924
#pragma line 573 "/usr/include/stdio.h" 3 4 ::: 926
#pragma line 594 "/usr/include/stdio.h" 3 4 ::: 935
#pragma line 622 "/usr/include/stdio.h" 3 4 ::: 956
#pragma line 638 "/usr/include/stdio.h" 3 4 ::: 959
#pragma line 665 "/usr/include/stdio.h" 3 4 ::: 961
#pragma line 689 "/usr/include/stdio.h" 3 4 ::: 978
#pragma line 737 "/usr/include/stdio.h" 3 4 ::: 1007
#pragma line 749 "/usr/include/stdio.h" 3 4 ::: 1012
#pragma line 773 "/usr/include/stdio.h" 3 4 ::: 1024
#pragma line 798 "/usr/include/stdio.h" 3 4 ::: 1031
#pragma line 826 "/usr/include/stdio.h" 3 4 ::: 1038
#pragma line 846 "/usr/include/stdio.h" 3 4 ::: 1051
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1060
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 3 4 ::: 1061
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1064
#pragma line 872 "/usr/include/stdio.h" 3 4 ::: 1075
#pragma line 912 "/usr/include/stdio.h" 3 4 ::: 1089
#pragma line 64 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/ap_cint.h" 2 ::: 1098
#pragma line 77 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/ap_cint.h" ::: 1099
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1100
#pragma line 57 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_apint.h" ::: 1101
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 1102
#pragma line 97 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" ::: 1103
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 1104
#pragma line 98 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 2143
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 2144
#pragma line 99 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3171
#pragma line 108 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" ::: 3172
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 3173
#pragma line 109 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4212
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 4213
#pragma line 110 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5240
#pragma line 131 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_dt.h" ::: 5241
#pragma line 58 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5244
#pragma line 1 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 5245
#pragma line 59 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5246
#pragma line 78 "/opt/Xilinx/Vivado/2018.1/common/technology/autopilot/ap_cint.h" 2 ::: 5247
#pragma line 5 "src/tdt.h" 2 ::: 5248
#pragma line 18 "src/tdt.h" ::: 5249
#pragma line 47 "src/tdt.c" 2 ::: 5259
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 5260
#pragma line 31 "/usr/include/math.h" 3 4 ::: 5261
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 5262
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 3 4 ::: 5263
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 5264
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 5265
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 5266
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 5270
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 5271
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 5273
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 5274
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 5275
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 5276
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 5279
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 5280
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 5283
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 5284
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 5288
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 5289
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 5292
#pragma line 83 "/usr/include/math.h" 3 4 ::: 5293
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5294
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5295
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5319
#pragma line 128 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5348
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5366
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5384
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5403
#pragma line 383 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5567
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 5569
#pragma line 104 "/usr/include/math.h" 3 4 ::: 5570
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5571
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5572
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5596
#pragma line 128 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5625
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5643
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5661
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5680
#pragma line 383 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5844
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 5846
#pragma line 151 "/usr/include/math.h" 3 4 ::: 5847
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5848
#pragma line 54 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5849
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5873
#pragma line 128 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5902
#pragma line 153 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5920
#pragma line 178 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5938
#pragma line 204 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5957
#pragma line 383 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 6121
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 6123
#pragma line 168 "/usr/include/math.h" 3 4 ::: 6124
#pragma line 209 "/usr/include/math.h" 3 4 ::: 6126
#pragma line 347 "/usr/include/math.h" 3 4 ::: 6145
#pragma line 372 "/usr/include/math.h" 3 4 ::: 6159
#pragma line 48 "src/tdt.c" 2 ::: 6174
#pragma line 1 "src/aux.h" 1 ::: 6175
#pragma line 49 "src/tdt.c" 2 ::: 6188
#pragma line 63 "src/tdt.c" ::: 6205
#pragma line 157 "src/tdt.c" ::: 6289
#pragma line 169 "src/tdt.c" ::: 6291
#pragma line 206 "src/tdt.c" ::: 6320
