// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="tdt,hls_ip_2018_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k325tffg676-2,HLS_INPUT_CLOCK=4.500000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.483750,HLS_SYN_LAT=11,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=25,HLS_SYN_FF=3863,HLS_SYN_LUT=3414}" *)

module tdt (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        w_div,
        h_div,
        d_w,
        d_h,
        s_w,
        s_h,
        M0,
        M1,
        M2,
        M3,
        M4,
        M5,
        c,
        r,
        hs_p,
        hs_p_ap_vld,
        hs,
        hs_ap_vld,
        ws,
        ws_ap_vld,
        tile_valid,
        tile_valid_ap_vld,
        left_col,
        left_col_ap_vld,
        top_row,
        top_row_ap_vld,
        baddr,
        baddr_ap_vld,
        cd0,
        cd0_ap_vld,
        cd1,
        cd1_ap_vld,
        cd2,
        cd2_ap_vld,
        cd3,
        cd3_ap_vld,
        mod_db,
        mod_db_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [7:0] w_div;
input  [7:0] h_div;
input  [12:0] d_w;
input  [12:0] d_h;
input  [12:0] s_w;
input  [12:0] s_h;
input  [26:0] M0;
input  [26:0] M1;
input  [26:0] M2;
input  [26:0] M3;
input  [26:0] M4;
input  [26:0] M5;
input  [7:0] c;
input  [7:0] r;
output  [14:0] hs_p;
output   hs_p_ap_vld;
output  [14:0] hs;
output   hs_ap_vld;
output  [14:0] ws;
output   ws_ap_vld;
output  [0:0] tile_valid;
output   tile_valid_ap_vld;
output  [11:0] left_col;
output   left_col_ap_vld;
output  [11:0] top_row;
output   top_row_ap_vld;
output  [31:0] baddr;
output   baddr_ap_vld;
output  [12:0] cd0;
output   cd0_ap_vld;
output  [12:0] cd1;
output   cd1_ap_vld;
output  [12:0] cd2;
output   cd2_ap_vld;
output  [12:0] cd3;
output   cd3_ap_vld;
output  [1:0] mod_db;
output   mod_db_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg hs_p_ap_vld;
reg hs_ap_vld;
reg ws_ap_vld;
reg tile_valid_ap_vld;
reg left_col_ap_vld;
reg top_row_ap_vld;
reg baddr_ap_vld;
reg cd0_ap_vld;
reg cd1_ap_vld;
reg cd2_ap_vld;
reg cd3_ap_vld;
reg mod_db_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
reg    ap_block_pp0_stage0_11001;
reg   [26:0] M5_read_reg_1359;
reg   [26:0] M5_read_reg_1359_pp0_iter1_reg;
reg   [26:0] M5_read_reg_1359_pp0_iter2_reg;
reg   [26:0] M5_read_reg_1359_pp0_iter3_reg;
reg   [26:0] M5_read_reg_1359_pp0_iter4_reg;
reg   [26:0] M5_read_reg_1359_pp0_iter5_reg;
reg   [26:0] M5_read_reg_1359_pp0_iter6_reg;
reg   [26:0] M4_read_reg_1364;
reg   [26:0] M4_read_reg_1364_pp0_iter1_reg;
reg   [26:0] M3_read_reg_1369;
reg   [26:0] M3_read_reg_1369_pp0_iter1_reg;
reg   [26:0] M2_read_reg_1374;
reg   [26:0] M2_read_reg_1374_pp0_iter1_reg;
reg   [26:0] M2_read_reg_1374_pp0_iter2_reg;
reg   [26:0] M2_read_reg_1374_pp0_iter3_reg;
reg   [26:0] M2_read_reg_1374_pp0_iter4_reg;
reg   [26:0] M2_read_reg_1374_pp0_iter5_reg;
reg   [26:0] M2_read_reg_1374_pp0_iter6_reg;
reg   [26:0] M1_read_reg_1379;
reg   [26:0] M1_read_reg_1379_pp0_iter1_reg;
reg   [26:0] M0_read_reg_1384;
reg   [26:0] M0_read_reg_1384_pp0_iter1_reg;
reg  signed [12:0] s_h_read_reg_1389;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter1_reg;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter2_reg;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter3_reg;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter4_reg;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter5_reg;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter6_reg;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter7_reg;
reg  signed [12:0] s_h_read_reg_1389_pp0_iter8_reg;
reg  signed [12:0] s_w_read_reg_1396;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter1_reg;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter2_reg;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter3_reg;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter4_reg;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter5_reg;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter6_reg;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter7_reg;
reg  signed [12:0] s_w_read_reg_1396_pp0_iter8_reg;
reg  signed [7:0] h_div_read_reg_1404;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter1_reg;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter2_reg;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter3_reg;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter4_reg;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter5_reg;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter6_reg;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter7_reg;
reg  signed [7:0] h_div_read_reg_1404_pp0_iter8_reg;
reg  signed [7:0] w_div_read_reg_1410;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter1_reg;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter2_reg;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter3_reg;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter4_reg;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter5_reg;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter6_reg;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter7_reg;
reg  signed [7:0] w_div_read_reg_1410_pp0_iter8_reg;
wire   [12:0] cd00_fu_308_p2;
reg   [12:0] cd00_reg_1416;
reg   [12:0] cd00_reg_1416_pp0_iter1_reg;
reg   [12:0] cd00_reg_1416_pp0_iter2_reg;
reg   [12:0] cd00_reg_1416_pp0_iter3_reg;
reg   [12:0] cd00_reg_1416_pp0_iter4_reg;
reg   [12:0] cd00_reg_1416_pp0_iter5_reg;
reg   [12:0] cd00_reg_1416_pp0_iter6_reg;
reg   [12:0] cd00_reg_1416_pp0_iter7_reg;
reg   [12:0] cd00_reg_1416_pp0_iter8_reg;
reg   [12:0] cd00_reg_1416_pp0_iter9_reg;
reg   [12:0] cd00_reg_1416_pp0_iter10_reg;
wire   [12:0] rd00_fu_322_p2;
reg   [12:0] rd00_reg_1424;
reg   [11:0] tmp_7_reg_1430;
reg   [11:0] tmp_3_reg_1435;
reg   [11:0] tmp_13_reg_1440;
reg   [11:0] tmp_13_reg_1440_pp0_iter1_reg;
reg   [11:0] tmp_13_reg_1440_pp0_iter2_reg;
reg   [11:0] tmp_13_reg_1440_pp0_iter3_reg;
reg   [11:0] tmp_13_reg_1440_pp0_iter4_reg;
reg   [11:0] tmp_13_reg_1440_pp0_iter5_reg;
reg   [11:0] tmp_13_reg_1440_pp0_iter6_reg;
reg   [11:0] tmp_14_reg_1445;
reg   [11:0] tmp_14_reg_1445_pp0_iter1_reg;
reg   [11:0] tmp_14_reg_1445_pp0_iter2_reg;
reg   [11:0] tmp_14_reg_1445_pp0_iter3_reg;
reg   [11:0] tmp_14_reg_1445_pp0_iter4_reg;
reg   [11:0] tmp_14_reg_1445_pp0_iter5_reg;
reg   [11:0] tmp_14_reg_1445_pp0_iter6_reg;
wire   [11:0] cl_fu_368_p1;
reg   [11:0] cl_reg_1450;
reg   [11:0] cl_reg_1450_pp0_iter1_reg;
reg   [11:0] cl_reg_1450_pp0_iter2_reg;
reg   [11:0] cl_reg_1450_pp0_iter3_reg;
reg   [11:0] cl_reg_1450_pp0_iter4_reg;
reg   [11:0] cl_reg_1450_pp0_iter5_reg;
reg   [11:0] cl_reg_1450_pp0_iter6_reg;
reg   [11:0] cl_reg_1450_pp0_iter7_reg;
reg   [11:0] cl_reg_1450_pp0_iter8_reg;
wire   [11:0] rt_fu_372_p1;
reg   [11:0] rt_reg_1456;
reg   [11:0] rt_reg_1456_pp0_iter1_reg;
reg   [11:0] rt_reg_1456_pp0_iter2_reg;
reg   [11:0] rt_reg_1456_pp0_iter3_reg;
reg   [11:0] rt_reg_1456_pp0_iter4_reg;
reg   [11:0] rt_reg_1456_pp0_iter5_reg;
reg   [11:0] rt_reg_1456_pp0_iter6_reg;
reg   [11:0] rt_reg_1456_pp0_iter7_reg;
reg   [11:0] rt_reg_1456_pp0_iter8_reg;
wire   [12:0] cd11_fu_389_p2;
reg   [12:0] cd11_reg_1462;
reg   [12:0] cd11_reg_1462_pp0_iter2_reg;
reg   [12:0] cd11_reg_1462_pp0_iter3_reg;
reg   [12:0] cd11_reg_1462_pp0_iter4_reg;
reg   [12:0] cd11_reg_1462_pp0_iter5_reg;
reg   [12:0] cd11_reg_1462_pp0_iter6_reg;
reg   [12:0] cd11_reg_1462_pp0_iter7_reg;
reg   [12:0] cd11_reg_1462_pp0_iter8_reg;
reg   [12:0] cd11_reg_1462_pp0_iter9_reg;
reg   [12:0] cd11_reg_1462_pp0_iter10_reg;
wire   [12:0] tmp_15_fu_418_p2;
reg   [12:0] tmp_15_reg_1468;
wire   [12:0] tmp_16_fu_423_p2;
reg   [12:0] tmp_16_reg_1473;
wire   [12:0] tmp_26_1_fu_428_p2;
reg   [12:0] tmp_26_1_reg_1478;
wire   [12:0] tmp_27_2_fu_434_p2;
reg   [12:0] tmp_27_2_reg_1483;
wire  signed [31:0] tmp_8_fu_440_p1;
wire  signed [31:0] tmp_2_fu_443_p1;
wire  signed [31:0] tmp_10_fu_446_p1;
wire  signed [31:0] tmp_11_fu_449_p1;
wire  signed [31:0] tmp_17_fu_452_p1;
wire  signed [31:0] tmp_19_fu_461_p1;
wire  signed [31:0] tmp_28_1_fu_482_p1;
wire  signed [31:0] tmp_30_2_fu_497_p1;
wire   [31:0] grp_fu_455_p2;
reg   [31:0] tmp_18_reg_1536;
wire   [31:0] grp_fu_464_p2;
reg   [31:0] tmp_20_reg_1541;
wire   [31:0] grp_fu_470_p2;
reg   [31:0] tmp_23_reg_1547;
wire   [31:0] grp_fu_476_p2;
reg   [31:0] tmp_24_reg_1552;
wire   [31:0] grp_fu_485_p2;
reg   [31:0] tmp_29_1_reg_1558;
wire   [31:0] grp_fu_491_p2;
reg   [31:0] tmp_35_1_reg_1563;
wire   [31:0] grp_fu_500_p2;
reg   [31:0] tmp_31_2_reg_1568;
wire   [31:0] grp_fu_506_p2;
reg   [31:0] tmp_36_2_reg_1574;
wire   [17:0] cs_0_fu_572_p2;
reg   [17:0] cs_0_reg_1580;
wire   [17:0] rs_0_fu_578_p2;
reg   [17:0] rs_0_reg_1587;
wire   [17:0] cs_1_fu_632_p2;
reg   [17:0] cs_1_reg_1594;
wire   [17:0] rs_1_fu_638_p2;
reg   [17:0] rs_1_reg_1601;
wire   [17:0] cs_2_fu_682_p2;
reg   [17:0] cs_2_reg_1608;
wire   [17:0] rs_2_fu_688_p2;
reg   [17:0] rs_2_reg_1615;
wire   [17:0] cs_3_fu_732_p2;
reg   [17:0] cs_3_reg_1622;
wire   [17:0] rs_3_fu_738_p2;
reg   [17:0] rs_3_reg_1629;
wire   [17:0] min1_fu_748_p3;
reg   [17:0] min1_reg_1636;
wire   [17:0] min2_fu_758_p3;
reg   [17:0] min2_reg_1641;
wire   [0:0] tmp_97_i_fu_764_p2;
reg   [0:0] tmp_97_i_reg_1646;
wire   [17:0] max1_fu_770_p3;
reg   [17:0] max1_reg_1651;
wire   [17:0] max2_fu_776_p3;
reg   [17:0] max2_reg_1657;
wire   [17:0] min1_1_fu_786_p3;
reg   [17:0] min1_1_reg_1663;
wire   [17:0] min2_2_fu_796_p3;
reg   [17:0] min2_2_reg_1668;
wire   [0:0] tmp_97_i1_fu_802_p2;
reg   [0:0] tmp_97_i1_reg_1673;
wire   [17:0] max1_2_fu_808_p3;
reg   [17:0] max1_2_reg_1678;
wire   [17:0] max2_1_fu_814_p3;
reg   [17:0] max2_1_reg_1684;
wire  signed [11:0] cl_1_fu_891_p3;
reg  signed [11:0] cl_1_reg_1695;
reg  signed [11:0] cl_1_reg_1695_pp0_iter10_reg;
wire  signed [11:0] rt_1_fu_992_p3;
reg  signed [11:0] rt_1_reg_1701;
reg  signed [11:0] rt_1_reg_1701_pp0_iter10_reg;
wire   [12:0] tmp_40_fu_1055_p2;
reg   [12:0] tmp_40_reg_1711;
reg   [12:0] tmp_40_reg_1711_pp0_iter10_reg;
wire   [12:0] tmp_43_fu_1069_p2;
reg   [12:0] tmp_43_reg_1718;
reg   [12:0] tmp_43_reg_1718_pp0_iter10_reg;
wire   [0:0] sel_tmp7_fu_1181_p2;
reg   [0:0] sel_tmp7_reg_1725;
reg   [0:0] sel_tmp7_reg_1725_pp0_iter10_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
wire   [1:0] m_fu_1256_p1;
wire  signed [7:0] tmp_fu_300_p0;
wire    ap_block_pp0_stage0;
wire  signed [7:0] cd00_fu_308_p0;
wire  signed [7:0] cd00_fu_308_p1;
wire  signed [7:0] tmp_5_fu_314_p0;
wire  signed [7:0] rd00_fu_322_p0;
wire  signed [7:0] rd00_fu_322_p1;
wire  signed [12:0] tmp_13_fu_348_p1;
wire  signed [12:0] tmp_14_fu_358_p1;
wire  signed [12:0] cl_fu_368_p0;
wire  signed [12:0] rt_fu_372_p0;
wire  signed [8:0] tmp_cast_fu_376_p1;
wire   [8:0] tmp1_fu_379_p2;
wire  signed [12:0] tmp21_cast_fu_385_p1;
wire  signed [8:0] tmp_5_cast_fu_394_p1;
wire   [8:0] tmp2_fu_397_p2;
wire  signed [12:0] tmp22_cast_fu_403_p1;
wire  signed [12:0] tmp_4_fu_412_p1;
wire  signed [12:0] tmp_s_fu_415_p1;
wire   [12:0] rd11_fu_407_p2;
wire  signed [26:0] grp_fu_455_p0;
wire  signed [12:0] grp_fu_455_p1;
wire  signed [26:0] grp_fu_464_p0;
wire  signed [12:0] grp_fu_464_p1;
wire  signed [26:0] grp_fu_470_p0;
wire  signed [12:0] grp_fu_470_p1;
wire  signed [26:0] grp_fu_476_p0;
wire  signed [12:0] grp_fu_476_p1;
wire  signed [26:0] grp_fu_485_p0;
wire  signed [12:0] grp_fu_485_p1;
wire  signed [26:0] grp_fu_491_p0;
wire  signed [12:0] grp_fu_491_p1;
wire  signed [26:0] grp_fu_500_p0;
wire  signed [12:0] grp_fu_500_p1;
wire  signed [26:0] grp_fu_506_p0;
wire  signed [12:0] grp_fu_506_p1;
wire  signed [31:0] tmp_9_fu_512_p1;
wire   [31:0] tmp_21_fu_524_p2;
wire  signed [31:0] tmp_12_fu_515_p1;
wire   [31:0] tmp_25_fu_534_p2;
wire   [31:0] tmp_22_fu_529_p2;
wire   [16:0] tmp_27_fu_544_p4;
wire   [31:0] tmp_26_fu_539_p2;
wire   [16:0] tmp_28_fu_558_p4;
wire  signed [17:0] tmp_40_cast_fu_554_p1;
wire  signed [17:0] tmp_17_cast_fu_518_p1;
wire  signed [17:0] tmp_43_cast_fu_568_p1;
wire  signed [17:0] tmp_20_cast_fu_521_p1;
wire   [31:0] tmp_32_1_fu_584_p2;
wire   [31:0] tmp_37_1_fu_594_p2;
wire   [31:0] tmp_33_1_fu_589_p2;
wire   [16:0] tmp_29_fu_604_p4;
wire   [31:0] tmp_38_1_fu_599_p2;
wire   [16:0] tmp_30_fu_618_p4;
wire  signed [17:0] tmp_46_cast_fu_614_p1;
wire  signed [17:0] tmp_53_cast_fu_628_p1;
wire   [31:0] tmp_33_2_fu_644_p2;
wire   [16:0] tmp_31_fu_654_p4;
wire   [31:0] tmp_38_2_fu_649_p2;
wire   [16:0] tmp_32_fu_668_p4;
wire  signed [17:0] tmp_58_cast_fu_664_p1;
wire  signed [17:0] tmp_65_cast_fu_678_p1;
wire   [31:0] tmp_33_3_fu_694_p2;
wire   [16:0] tmp_33_fu_704_p4;
wire   [31:0] tmp_38_3_fu_699_p2;
wire   [16:0] tmp_34_fu_718_p4;
wire  signed [17:0] tmp_76_cast_fu_714_p1;
wire  signed [17:0] tmp_86_cast_fu_728_p1;
wire   [0:0] tmp_i_fu_744_p2;
wire   [0:0] tmp_i_6_fu_754_p2;
wire   [0:0] tmp_i1_fu_782_p2;
wire   [0:0] tmp_i1_7_fu_792_p2;
wire  signed [17:0] min2_1_fu_841_p3;
wire  signed [25:0] min2_1_cast_fu_846_p1;
wire   [26:0] tmp_24_cast_fu_858_p1;
wire  signed [26:0] tmp_16_cast_fu_829_p1;
wire   [0:0] tmp_35_fu_850_p3;
wire   [0:0] tmp_36_fu_862_p2;
wire   [0:0] sel_tmp_fu_872_p2;
wire   [0:0] sel_tmp1_fu_878_p2;
wire   [11:0] cl_2_fu_868_p1;
wire   [11:0] cl_3_fu_884_p3;
wire   [0:0] tmp_98_i_fu_899_p2;
wire   [17:0] max1_1_fu_903_p3;
wire  signed [17:0] tmp_16_cast3_fu_826_p1;
wire   [0:0] tmp_42_fu_915_p3;
wire   [11:0] cr_2_fu_923_p1;
wire   [0:0] tmp_37_fu_909_p2;
wire   [11:0] p_cr_2_fu_927_p3;
wire  signed [17:0] min2_3_fu_942_p3;
wire  signed [25:0] min2_3_cast_fu_947_p1;
wire   [26:0] tmp_57_cast_fu_959_p1;
wire  signed [26:0] tmp_19_cast_fu_838_p1;
wire   [0:0] tmp_61_fu_951_p3;
wire   [0:0] tmp_38_fu_963_p2;
wire   [0:0] sel_tmp5_fu_973_p2;
wire   [0:0] sel_tmp6_fu_979_p2;
wire   [11:0] rt_2_fu_969_p1;
wire   [11:0] rt_3_fu_985_p3;
wire   [0:0] tmp_98_i1_fu_1000_p2;
wire   [17:0] max1_3_fu_1004_p3;
wire  signed [17:0] tmp_19_cast2_fu_835_p1;
wire   [0:0] tmp_64_fu_1016_p3;
wire   [11:0] rb_2_fu_1024_p1;
wire   [0:0] tmp_39_fu_1010_p2;
wire   [11:0] p_rb_2_fu_1028_p3;
wire   [11:0] rb_1_fu_1036_p3;
wire  signed [12:0] tmp_66_cast_fu_1047_p1;
wire  signed [12:0] tmp_68_cast_fu_1051_p1;
wire   [11:0] cr_1_fu_935_p3;
wire  signed [12:0] tmp_70_cast_fu_1061_p1;
wire  signed [12:0] tmp_71_cast_fu_1065_p1;
wire  signed [10:0] tmp_46_fu_1075_p3;
wire  signed [13:0] tmp_78_cast1_fu_1082_p1;
wire  signed [13:0] tmp_16_cast2_fu_823_p1;
wire   [13:0] tmp_47_fu_1090_p2;
wire  signed [17:0] tmp_79_cast_fu_1096_p1;
wire  signed [11:0] tmp_78_cast_fu_1086_p1;
wire   [11:0] tmp_49_fu_1106_p2;
wire  signed [17:0] tmp_81_cast_fu_1112_p1;
wire  signed [10:0] tmp_51_fu_1122_p3;
wire  signed [11:0] tmp_88_cast_fu_1133_p1;
wire   [11:0] tmp_52_fu_1137_p2;
wire  signed [17:0] tmp_89_cast_fu_1143_p1;
wire  signed [13:0] tmp_88_cast1_fu_1129_p1;
wire  signed [13:0] tmp_19_cast1_fu_832_p1;
wire   [13:0] tmp_54_fu_1153_p2;
wire  signed [17:0] tmp_93_cast_fu_1159_p1;
wire   [0:0] tmp_48_fu_1100_p2;
wire   [0:0] tmp_50_fu_1116_p2;
wire   [0:0] tmp_53_fu_1147_p2;
wire   [0:0] tmp_55_fu_1163_p2;
wire   [0:0] tmp4_fu_1175_p2;
wire   [0:0] tmp3_fu_1169_p2;
wire   [0:0] abscond_fu_1187_p2;
wire   [12:0] tmp_41_fu_1192_p2;
wire  signed [12:0] s_tile_h_fu_1197_p3;
wire   [0:0] abscond1_fu_1216_p2;
wire   [12:0] tmp_44_fu_1221_p2;
wire  signed [12:0] s_tile_w_r2_9_fu_1226_p3;
wire   [0:0] tmp_45_fu_1237_p2;
wire   [11:0] tmp_66_fu_1209_p1;
wire   [11:0] s_tile_h_1_fu_1243_p3;
wire  signed [13:0] s_tile_w_r2_5_cast_fu_1233_p1;
wire   [0:0] sel_tmp2_fu_1285_p2;
wire   [13:0] s_tile_w_r2_3_fu_1279_p2;
wire   [0:0] sel_tmp4_fu_1299_p2;
wire   [13:0] s_tile_w_r2_2_fu_1273_p2;
wire   [13:0] s_tile_w_r2_5_fu_1291_p3;
wire   [0:0] sel_tmp8_fu_1313_p2;
wire   [13:0] s_tile_w_r2_1_fu_1267_p2;
wire   [13:0] s_tile_w_r2_6_fu_1305_p3;
wire   [0:0] sel_tmp3_fu_1327_p2;
wire   [13:0] s_tile_w_r2_fu_1261_p2;
wire   [13:0] s_tile_w_r2_7_fu_1319_p3;
wire   [13:0] s_tile_w_r2_8_fu_1333_p3;
wire  signed [24:0] grp_fu_1350_p3;
reg    grp_fu_455_ce;
reg    grp_fu_464_ce;
reg    grp_fu_470_ce;
reg    grp_fu_476_ce;
reg    grp_fu_485_ce;
reg    grp_fu_491_ce;
reg    grp_fu_500_ce;
reg    grp_fu_506_ce;
reg    grp_fu_1350_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to10;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
end

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_455_p0),
    .din1(grp_fu_455_p1),
    .ce(grp_fu_455_ce),
    .dout(grp_fu_455_p2)
);

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_464_p0),
    .din1(grp_fu_464_p1),
    .ce(grp_fu_464_ce),
    .dout(grp_fu_464_p2)
);

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_470_p0),
    .din1(grp_fu_470_p1),
    .ce(grp_fu_470_ce),
    .dout(grp_fu_470_p2)
);

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_476_p0),
    .din1(grp_fu_476_p1),
    .ce(grp_fu_476_ce),
    .dout(grp_fu_476_p2)
);

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_485_p0),
    .din1(grp_fu_485_p1),
    .ce(grp_fu_485_ce),
    .dout(grp_fu_485_p2)
);

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_491_p0),
    .din1(grp_fu_491_p1),
    .ce(grp_fu_491_ce),
    .dout(grp_fu_491_p2)
);

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_500_p0),
    .din1(grp_fu_500_p1),
    .ce(grp_fu_500_ce),
    .dout(grp_fu_500_p2)
);

tdt_mul_27s_13s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
tdt_mul_27s_13s_3bkb_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_506_p0),
    .din1(grp_fu_506_p1),
    .ce(grp_fu_506_ce),
    .dout(grp_fu_506_p2)
);

tdt_mac_muladd_13cud #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 25 ))
tdt_mac_muladd_13cud_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(s_w_read_reg_1396_pp0_iter8_reg),
    .din1(rt_1_fu_992_p3),
    .din2(cl_1_reg_1695_pp0_iter10_reg),
    .ce(grp_fu_1350_ce),
    .dout(grp_fu_1350_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        if ((1'b1 == ap_ce)) begin
            ap_CS_fsm <= ap_NS_fsm;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        M0_read_reg_1384 <= M0;
        M0_read_reg_1384_pp0_iter1_reg <= M0_read_reg_1384;
        M1_read_reg_1379 <= M1;
        M1_read_reg_1379_pp0_iter1_reg <= M1_read_reg_1379;
        M2_read_reg_1374 <= M2;
        M2_read_reg_1374_pp0_iter1_reg <= M2_read_reg_1374;
        M3_read_reg_1369 <= M3;
        M3_read_reg_1369_pp0_iter1_reg <= M3_read_reg_1369;
        M4_read_reg_1364 <= M4;
        M4_read_reg_1364_pp0_iter1_reg <= M4_read_reg_1364;
        M5_read_reg_1359 <= M5;
        M5_read_reg_1359_pp0_iter1_reg <= M5_read_reg_1359;
        cd00_reg_1416 <= cd00_fu_308_p2;
        cd00_reg_1416_pp0_iter1_reg <= cd00_reg_1416;
        cd11_reg_1462 <= cd11_fu_389_p2;
        cl_reg_1450 <= cl_fu_368_p1;
        cl_reg_1450_pp0_iter1_reg <= cl_reg_1450;
        h_div_read_reg_1404 <= h_div;
        h_div_read_reg_1404_pp0_iter1_reg <= h_div_read_reg_1404;
        rd00_reg_1424 <= rd00_fu_322_p2;
        rt_reg_1456 <= rt_fu_372_p1;
        rt_reg_1456_pp0_iter1_reg <= rt_reg_1456;
        s_h_read_reg_1389 <= s_h;
        s_h_read_reg_1389_pp0_iter1_reg <= s_h_read_reg_1389;
        s_w_read_reg_1396 <= s_w;
        s_w_read_reg_1396_pp0_iter1_reg <= s_w_read_reg_1396;
        tmp_13_reg_1440 <= {{tmp_13_fu_348_p1[12:1]}};
        tmp_13_reg_1440_pp0_iter1_reg <= tmp_13_reg_1440;
        tmp_14_reg_1445 <= {{tmp_14_fu_358_p1[12:1]}};
        tmp_14_reg_1445_pp0_iter1_reg <= tmp_14_reg_1445;
        tmp_15_reg_1468 <= tmp_15_fu_418_p2;
        tmp_16_reg_1473 <= tmp_16_fu_423_p2;
        tmp_26_1_reg_1478 <= tmp_26_1_fu_428_p2;
        tmp_27_2_reg_1483 <= tmp_27_2_fu_434_p2;
        tmp_3_reg_1435 <= {{d_h[12:1]}};
        tmp_7_reg_1430 <= {{d_w[12:1]}};
        w_div_read_reg_1410 <= w_div;
        w_div_read_reg_1410_pp0_iter1_reg <= w_div_read_reg_1410;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        M2_read_reg_1374_pp0_iter2_reg <= M2_read_reg_1374_pp0_iter1_reg;
        M2_read_reg_1374_pp0_iter3_reg <= M2_read_reg_1374_pp0_iter2_reg;
        M2_read_reg_1374_pp0_iter4_reg <= M2_read_reg_1374_pp0_iter3_reg;
        M2_read_reg_1374_pp0_iter5_reg <= M2_read_reg_1374_pp0_iter4_reg;
        M2_read_reg_1374_pp0_iter6_reg <= M2_read_reg_1374_pp0_iter5_reg;
        M5_read_reg_1359_pp0_iter2_reg <= M5_read_reg_1359_pp0_iter1_reg;
        M5_read_reg_1359_pp0_iter3_reg <= M5_read_reg_1359_pp0_iter2_reg;
        M5_read_reg_1359_pp0_iter4_reg <= M5_read_reg_1359_pp0_iter3_reg;
        M5_read_reg_1359_pp0_iter5_reg <= M5_read_reg_1359_pp0_iter4_reg;
        M5_read_reg_1359_pp0_iter6_reg <= M5_read_reg_1359_pp0_iter5_reg;
        cd00_reg_1416_pp0_iter10_reg <= cd00_reg_1416_pp0_iter9_reg;
        cd00_reg_1416_pp0_iter2_reg <= cd00_reg_1416_pp0_iter1_reg;
        cd00_reg_1416_pp0_iter3_reg <= cd00_reg_1416_pp0_iter2_reg;
        cd00_reg_1416_pp0_iter4_reg <= cd00_reg_1416_pp0_iter3_reg;
        cd00_reg_1416_pp0_iter5_reg <= cd00_reg_1416_pp0_iter4_reg;
        cd00_reg_1416_pp0_iter6_reg <= cd00_reg_1416_pp0_iter5_reg;
        cd00_reg_1416_pp0_iter7_reg <= cd00_reg_1416_pp0_iter6_reg;
        cd00_reg_1416_pp0_iter8_reg <= cd00_reg_1416_pp0_iter7_reg;
        cd00_reg_1416_pp0_iter9_reg <= cd00_reg_1416_pp0_iter8_reg;
        cd11_reg_1462_pp0_iter10_reg <= cd11_reg_1462_pp0_iter9_reg;
        cd11_reg_1462_pp0_iter2_reg <= cd11_reg_1462;
        cd11_reg_1462_pp0_iter3_reg <= cd11_reg_1462_pp0_iter2_reg;
        cd11_reg_1462_pp0_iter4_reg <= cd11_reg_1462_pp0_iter3_reg;
        cd11_reg_1462_pp0_iter5_reg <= cd11_reg_1462_pp0_iter4_reg;
        cd11_reg_1462_pp0_iter6_reg <= cd11_reg_1462_pp0_iter5_reg;
        cd11_reg_1462_pp0_iter7_reg <= cd11_reg_1462_pp0_iter6_reg;
        cd11_reg_1462_pp0_iter8_reg <= cd11_reg_1462_pp0_iter7_reg;
        cd11_reg_1462_pp0_iter9_reg <= cd11_reg_1462_pp0_iter8_reg;
        cl_1_reg_1695 <= cl_1_fu_891_p3;
        cl_1_reg_1695_pp0_iter10_reg <= cl_1_reg_1695;
        cl_reg_1450_pp0_iter2_reg <= cl_reg_1450_pp0_iter1_reg;
        cl_reg_1450_pp0_iter3_reg <= cl_reg_1450_pp0_iter2_reg;
        cl_reg_1450_pp0_iter4_reg <= cl_reg_1450_pp0_iter3_reg;
        cl_reg_1450_pp0_iter5_reg <= cl_reg_1450_pp0_iter4_reg;
        cl_reg_1450_pp0_iter6_reg <= cl_reg_1450_pp0_iter5_reg;
        cl_reg_1450_pp0_iter7_reg <= cl_reg_1450_pp0_iter6_reg;
        cl_reg_1450_pp0_iter8_reg <= cl_reg_1450_pp0_iter7_reg;
        cs_0_reg_1580 <= cs_0_fu_572_p2;
        cs_1_reg_1594 <= cs_1_fu_632_p2;
        cs_2_reg_1608 <= cs_2_fu_682_p2;
        cs_3_reg_1622 <= cs_3_fu_732_p2;
        h_div_read_reg_1404_pp0_iter2_reg <= h_div_read_reg_1404_pp0_iter1_reg;
        h_div_read_reg_1404_pp0_iter3_reg <= h_div_read_reg_1404_pp0_iter2_reg;
        h_div_read_reg_1404_pp0_iter4_reg <= h_div_read_reg_1404_pp0_iter3_reg;
        h_div_read_reg_1404_pp0_iter5_reg <= h_div_read_reg_1404_pp0_iter4_reg;
        h_div_read_reg_1404_pp0_iter6_reg <= h_div_read_reg_1404_pp0_iter5_reg;
        h_div_read_reg_1404_pp0_iter7_reg <= h_div_read_reg_1404_pp0_iter6_reg;
        h_div_read_reg_1404_pp0_iter8_reg <= h_div_read_reg_1404_pp0_iter7_reg;
        max1_2_reg_1678 <= max1_2_fu_808_p3;
        max1_reg_1651 <= max1_fu_770_p3;
        max2_1_reg_1684 <= max2_1_fu_814_p3;
        max2_reg_1657 <= max2_fu_776_p3;
        min1_1_reg_1663 <= min1_1_fu_786_p3;
        min1_reg_1636 <= min1_fu_748_p3;
        min2_2_reg_1668 <= min2_2_fu_796_p3;
        min2_reg_1641 <= min2_fu_758_p3;
        rs_0_reg_1587 <= rs_0_fu_578_p2;
        rs_1_reg_1601 <= rs_1_fu_638_p2;
        rs_2_reg_1615 <= rs_2_fu_688_p2;
        rs_3_reg_1629 <= rs_3_fu_738_p2;
        rt_1_reg_1701 <= rt_1_fu_992_p3;
        rt_1_reg_1701_pp0_iter10_reg <= rt_1_reg_1701;
        rt_reg_1456_pp0_iter2_reg <= rt_reg_1456_pp0_iter1_reg;
        rt_reg_1456_pp0_iter3_reg <= rt_reg_1456_pp0_iter2_reg;
        rt_reg_1456_pp0_iter4_reg <= rt_reg_1456_pp0_iter3_reg;
        rt_reg_1456_pp0_iter5_reg <= rt_reg_1456_pp0_iter4_reg;
        rt_reg_1456_pp0_iter6_reg <= rt_reg_1456_pp0_iter5_reg;
        rt_reg_1456_pp0_iter7_reg <= rt_reg_1456_pp0_iter6_reg;
        rt_reg_1456_pp0_iter8_reg <= rt_reg_1456_pp0_iter7_reg;
        s_h_read_reg_1389_pp0_iter2_reg <= s_h_read_reg_1389_pp0_iter1_reg;
        s_h_read_reg_1389_pp0_iter3_reg <= s_h_read_reg_1389_pp0_iter2_reg;
        s_h_read_reg_1389_pp0_iter4_reg <= s_h_read_reg_1389_pp0_iter3_reg;
        s_h_read_reg_1389_pp0_iter5_reg <= s_h_read_reg_1389_pp0_iter4_reg;
        s_h_read_reg_1389_pp0_iter6_reg <= s_h_read_reg_1389_pp0_iter5_reg;
        s_h_read_reg_1389_pp0_iter7_reg <= s_h_read_reg_1389_pp0_iter6_reg;
        s_h_read_reg_1389_pp0_iter8_reg <= s_h_read_reg_1389_pp0_iter7_reg;
        s_w_read_reg_1396_pp0_iter2_reg <= s_w_read_reg_1396_pp0_iter1_reg;
        s_w_read_reg_1396_pp0_iter3_reg <= s_w_read_reg_1396_pp0_iter2_reg;
        s_w_read_reg_1396_pp0_iter4_reg <= s_w_read_reg_1396_pp0_iter3_reg;
        s_w_read_reg_1396_pp0_iter5_reg <= s_w_read_reg_1396_pp0_iter4_reg;
        s_w_read_reg_1396_pp0_iter6_reg <= s_w_read_reg_1396_pp0_iter5_reg;
        s_w_read_reg_1396_pp0_iter7_reg <= s_w_read_reg_1396_pp0_iter6_reg;
        s_w_read_reg_1396_pp0_iter8_reg <= s_w_read_reg_1396_pp0_iter7_reg;
        sel_tmp7_reg_1725 <= sel_tmp7_fu_1181_p2;
        sel_tmp7_reg_1725_pp0_iter10_reg <= sel_tmp7_reg_1725;
        tmp_13_reg_1440_pp0_iter2_reg <= tmp_13_reg_1440_pp0_iter1_reg;
        tmp_13_reg_1440_pp0_iter3_reg <= tmp_13_reg_1440_pp0_iter2_reg;
        tmp_13_reg_1440_pp0_iter4_reg <= tmp_13_reg_1440_pp0_iter3_reg;
        tmp_13_reg_1440_pp0_iter5_reg <= tmp_13_reg_1440_pp0_iter4_reg;
        tmp_13_reg_1440_pp0_iter6_reg <= tmp_13_reg_1440_pp0_iter5_reg;
        tmp_14_reg_1445_pp0_iter2_reg <= tmp_14_reg_1445_pp0_iter1_reg;
        tmp_14_reg_1445_pp0_iter3_reg <= tmp_14_reg_1445_pp0_iter2_reg;
        tmp_14_reg_1445_pp0_iter4_reg <= tmp_14_reg_1445_pp0_iter3_reg;
        tmp_14_reg_1445_pp0_iter5_reg <= tmp_14_reg_1445_pp0_iter4_reg;
        tmp_14_reg_1445_pp0_iter6_reg <= tmp_14_reg_1445_pp0_iter5_reg;
        tmp_18_reg_1536 <= grp_fu_455_p2;
        tmp_20_reg_1541 <= grp_fu_464_p2;
        tmp_23_reg_1547 <= grp_fu_470_p2;
        tmp_24_reg_1552 <= grp_fu_476_p2;
        tmp_29_1_reg_1558 <= grp_fu_485_p2;
        tmp_31_2_reg_1568 <= grp_fu_500_p2;
        tmp_35_1_reg_1563 <= grp_fu_491_p2;
        tmp_36_2_reg_1574 <= grp_fu_506_p2;
        tmp_40_reg_1711 <= tmp_40_fu_1055_p2;
        tmp_40_reg_1711_pp0_iter10_reg <= tmp_40_reg_1711;
        tmp_43_reg_1718 <= tmp_43_fu_1069_p2;
        tmp_43_reg_1718_pp0_iter10_reg <= tmp_43_reg_1718;
        tmp_97_i1_reg_1673 <= tmp_97_i1_fu_802_p2;
        tmp_97_i_reg_1646 <= tmp_97_i_fu_764_p2;
        w_div_read_reg_1410_pp0_iter2_reg <= w_div_read_reg_1410_pp0_iter1_reg;
        w_div_read_reg_1410_pp0_iter3_reg <= w_div_read_reg_1410_pp0_iter2_reg;
        w_div_read_reg_1410_pp0_iter4_reg <= w_div_read_reg_1410_pp0_iter3_reg;
        w_div_read_reg_1410_pp0_iter5_reg <= w_div_read_reg_1410_pp0_iter4_reg;
        w_div_read_reg_1410_pp0_iter6_reg <= w_div_read_reg_1410_pp0_iter5_reg;
        w_div_read_reg_1410_pp0_iter7_reg <= w_div_read_reg_1410_pp0_iter6_reg;
        w_div_read_reg_1410_pp0_iter8_reg <= w_div_read_reg_1410_pp0_iter7_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to10 = 1'b1;
    end else begin
        ap_idle_pp0_0to10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to10 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        baddr_ap_vld = 1'b1;
    end else begin
        baddr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        cd0_ap_vld = 1'b1;
    end else begin
        cd0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        cd1_ap_vld = 1'b1;
    end else begin
        cd1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        cd2_ap_vld = 1'b1;
    end else begin
        cd2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        cd3_ap_vld = 1'b1;
    end else begin
        cd3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1350_ce = 1'b1;
    end else begin
        grp_fu_1350_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_455_ce = 1'b1;
    end else begin
        grp_fu_455_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_464_ce = 1'b1;
    end else begin
        grp_fu_464_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_470_ce = 1'b1;
    end else begin
        grp_fu_470_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_476_ce = 1'b1;
    end else begin
        grp_fu_476_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_485_ce = 1'b1;
    end else begin
        grp_fu_485_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_491_ce = 1'b1;
    end else begin
        grp_fu_491_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_500_ce = 1'b1;
    end else begin
        grp_fu_500_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_506_ce = 1'b1;
    end else begin
        grp_fu_506_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        hs_ap_vld = 1'b1;
    end else begin
        hs_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        hs_p_ap_vld = 1'b1;
    end else begin
        hs_p_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        left_col_ap_vld = 1'b1;
    end else begin
        left_col_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        mod_db_ap_vld = 1'b1;
    end else begin
        mod_db_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        tile_valid_ap_vld = 1'b1;
    end else begin
        tile_valid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        top_row_ap_vld = 1'b1;
    end else begin
        top_row_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        ws_ap_vld = 1'b1;
    end else begin
        ws_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abscond1_fu_1216_p2 = (($signed(tmp_43_reg_1718_pp0_iter10_reg) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign abscond_fu_1187_p2 = (($signed(tmp_40_reg_1711_pp0_iter10_reg) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign baddr = $signed(grp_fu_1350_p3);

assign cd0 = cd00_reg_1416_pp0_iter10_reg;

assign cd00_fu_308_p0 = tmp_fu_300_p0;

assign cd00_fu_308_p1 = c;

assign cd00_fu_308_p2 = ($signed(cd00_fu_308_p0) * $signed(cd00_fu_308_p1));

assign cd1 = cd11_reg_1462_pp0_iter10_reg;

assign cd11_fu_389_p2 = ($signed(tmp21_cast_fu_385_p1) + $signed(cd00_reg_1416));

assign cd2 = cd00_reg_1416_pp0_iter10_reg;

assign cd3 = cd11_reg_1462_pp0_iter10_reg;

assign cl_1_fu_891_p3 = ((tmp_35_fu_850_p3[0:0] === 1'b1) ? 12'd0 : cl_3_fu_884_p3);

assign cl_2_fu_868_p1 = min2_1_fu_841_p3[11:0];

assign cl_3_fu_884_p3 = ((sel_tmp1_fu_878_p2[0:0] === 1'b1) ? cl_reg_1450_pp0_iter8_reg : cl_2_fu_868_p1);

assign cl_fu_368_p0 = s_w;

assign cl_fu_368_p1 = cl_fu_368_p0[11:0];

assign cr_1_fu_935_p3 = ((tmp_37_fu_909_p2[0:0] === 1'b1) ? cl_reg_1450_pp0_iter8_reg : p_cr_2_fu_927_p3);

assign cr_2_fu_923_p1 = max1_1_fu_903_p3[11:0];

assign cs_0_fu_572_p2 = ($signed(tmp_40_cast_fu_554_p1) + $signed(tmp_17_cast_fu_518_p1));

assign cs_1_fu_632_p2 = ($signed(tmp_46_cast_fu_614_p1) + $signed(tmp_17_cast_fu_518_p1));

assign cs_2_fu_682_p2 = ($signed(tmp_58_cast_fu_664_p1) + $signed(tmp_17_cast_fu_518_p1));

assign cs_3_fu_732_p2 = ($signed(tmp_76_cast_fu_714_p1) + $signed(tmp_17_cast_fu_518_p1));

assign grp_fu_455_p0 = tmp_8_fu_440_p1;

assign grp_fu_455_p1 = tmp_17_fu_452_p1;

assign grp_fu_464_p0 = tmp_2_fu_443_p1;

assign grp_fu_464_p1 = tmp_19_fu_461_p1;

assign grp_fu_470_p0 = tmp_10_fu_446_p1;

assign grp_fu_470_p1 = tmp_17_fu_452_p1;

assign grp_fu_476_p0 = tmp_11_fu_449_p1;

assign grp_fu_476_p1 = tmp_19_fu_461_p1;

assign grp_fu_485_p0 = tmp_8_fu_440_p1;

assign grp_fu_485_p1 = tmp_28_1_fu_482_p1;

assign grp_fu_491_p0 = tmp_10_fu_446_p1;

assign grp_fu_491_p1 = tmp_28_1_fu_482_p1;

assign grp_fu_500_p0 = tmp_2_fu_443_p1;

assign grp_fu_500_p1 = tmp_30_2_fu_497_p1;

assign grp_fu_506_p0 = tmp_11_fu_449_p1;

assign grp_fu_506_p1 = tmp_30_2_fu_497_p1;

assign hs = s_tile_h_1_fu_1243_p3;

assign hs_p = $signed(s_tile_h_fu_1197_p3);

assign left_col = cl_1_reg_1695_pp0_iter10_reg;

assign m_fu_1256_p1 = s_tile_w_r2_9_fu_1226_p3[1:0];

assign max1_1_fu_903_p3 = ((tmp_98_i_fu_899_p2[0:0] === 1'b1) ? max1_reg_1651 : max2_reg_1657);

assign max1_2_fu_808_p3 = ((tmp_i1_fu_782_p2[0:0] === 1'b1) ? rs_0_reg_1587 : rs_1_reg_1601);

assign max1_3_fu_1004_p3 = ((tmp_98_i1_fu_1000_p2[0:0] === 1'b1) ? max1_2_reg_1678 : max2_1_reg_1684);

assign max1_fu_770_p3 = ((tmp_i_fu_744_p2[0:0] === 1'b1) ? cs_0_reg_1580 : cs_1_reg_1594);

assign max2_1_fu_814_p3 = ((tmp_i1_7_fu_792_p2[0:0] === 1'b1) ? rs_2_reg_1615 : rs_3_reg_1629);

assign max2_fu_776_p3 = ((tmp_i_6_fu_754_p2[0:0] === 1'b1) ? cs_2_reg_1608 : cs_3_reg_1622);

assign min1_1_fu_786_p3 = ((tmp_i1_fu_782_p2[0:0] === 1'b1) ? rs_1_reg_1601 : rs_0_reg_1587);

assign min1_fu_748_p3 = ((tmp_i_fu_744_p2[0:0] === 1'b1) ? cs_1_reg_1594 : cs_0_reg_1580);

assign min2_1_cast_fu_846_p1 = min2_1_fu_841_p3;

assign min2_1_fu_841_p3 = ((tmp_97_i_reg_1646[0:0] === 1'b1) ? min2_reg_1641 : min1_reg_1636);

assign min2_2_fu_796_p3 = ((tmp_i1_7_fu_792_p2[0:0] === 1'b1) ? rs_3_reg_1629 : rs_2_reg_1615);

assign min2_3_cast_fu_947_p1 = min2_3_fu_942_p3;

assign min2_3_fu_942_p3 = ((tmp_97_i1_reg_1673[0:0] === 1'b1) ? min2_2_reg_1668 : min1_1_reg_1663);

assign min2_fu_758_p3 = ((tmp_i_6_fu_754_p2[0:0] === 1'b1) ? cs_3_reg_1622 : cs_2_reg_1608);

assign mod_db = m_fu_1256_p1;

assign p_cr_2_fu_927_p3 = ((tmp_42_fu_915_p3[0:0] === 1'b1) ? 12'd0 : cr_2_fu_923_p1);

assign p_rb_2_fu_1028_p3 = ((tmp_64_fu_1016_p3[0:0] === 1'b1) ? 12'd0 : rb_2_fu_1024_p1);

assign rb_1_fu_1036_p3 = ((tmp_39_fu_1010_p2[0:0] === 1'b1) ? rt_reg_1456_pp0_iter8_reg : p_rb_2_fu_1028_p3);

assign rb_2_fu_1024_p1 = max1_3_fu_1004_p3[11:0];

assign rd00_fu_322_p0 = tmp_5_fu_314_p0;

assign rd00_fu_322_p1 = r;

assign rd00_fu_322_p2 = ($signed(rd00_fu_322_p0) * $signed(rd00_fu_322_p1));

assign rd11_fu_407_p2 = ($signed(tmp22_cast_fu_403_p1) + $signed(rd00_reg_1424));

assign rs_0_fu_578_p2 = ($signed(tmp_43_cast_fu_568_p1) + $signed(tmp_20_cast_fu_521_p1));

assign rs_1_fu_638_p2 = ($signed(tmp_53_cast_fu_628_p1) + $signed(tmp_20_cast_fu_521_p1));

assign rs_2_fu_688_p2 = ($signed(tmp_65_cast_fu_678_p1) + $signed(tmp_20_cast_fu_521_p1));

assign rs_3_fu_738_p2 = ($signed(tmp_86_cast_fu_728_p1) + $signed(tmp_20_cast_fu_521_p1));

assign rt_1_fu_992_p3 = ((tmp_61_fu_951_p3[0:0] === 1'b1) ? 12'd0 : rt_3_fu_985_p3);

assign rt_2_fu_969_p1 = min2_3_fu_942_p3[11:0];

assign rt_3_fu_985_p3 = ((sel_tmp6_fu_979_p2[0:0] === 1'b1) ? rt_reg_1456_pp0_iter8_reg : rt_2_fu_969_p1);

assign rt_fu_372_p0 = s_h;

assign rt_fu_372_p1 = rt_fu_372_p0[11:0];

assign s_tile_h_1_fu_1243_p3 = ((tmp_45_fu_1237_p2[0:0] === 1'b1) ? 12'd1 : tmp_66_fu_1209_p1);

assign s_tile_h_fu_1197_p3 = ((abscond_fu_1187_p2[0:0] === 1'b1) ? tmp_40_reg_1711_pp0_iter10_reg : tmp_41_fu_1192_p2);

assign s_tile_w_r2_1_fu_1267_p2 = ($signed(14'd5) + $signed(s_tile_w_r2_5_cast_fu_1233_p1));

assign s_tile_w_r2_2_fu_1273_p2 = ($signed(14'd4) + $signed(s_tile_w_r2_5_cast_fu_1233_p1));

assign s_tile_w_r2_3_fu_1279_p2 = ($signed(14'd3) + $signed(s_tile_w_r2_5_cast_fu_1233_p1));

assign s_tile_w_r2_5_cast_fu_1233_p1 = s_tile_w_r2_9_fu_1226_p3;

assign s_tile_w_r2_5_fu_1291_p3 = ((sel_tmp2_fu_1285_p2[0:0] === 1'b1) ? s_tile_w_r2_3_fu_1279_p2 : s_tile_w_r2_5_cast_fu_1233_p1);

assign s_tile_w_r2_6_fu_1305_p3 = ((sel_tmp4_fu_1299_p2[0:0] === 1'b1) ? s_tile_w_r2_2_fu_1273_p2 : s_tile_w_r2_5_fu_1291_p3);

assign s_tile_w_r2_7_fu_1319_p3 = ((sel_tmp8_fu_1313_p2[0:0] === 1'b1) ? s_tile_w_r2_1_fu_1267_p2 : s_tile_w_r2_6_fu_1305_p3);

assign s_tile_w_r2_8_fu_1333_p3 = ((sel_tmp3_fu_1327_p2[0:0] === 1'b1) ? s_tile_w_r2_fu_1261_p2 : s_tile_w_r2_7_fu_1319_p3);

assign s_tile_w_r2_9_fu_1226_p3 = ((abscond1_fu_1216_p2[0:0] === 1'b1) ? tmp_43_reg_1718_pp0_iter10_reg : tmp_44_fu_1221_p2);

assign s_tile_w_r2_fu_1261_p2 = ($signed(14'd2) + $signed(s_tile_w_r2_5_cast_fu_1233_p1));

assign sel_tmp1_fu_878_p2 = (tmp_36_fu_862_p2 & sel_tmp_fu_872_p2);

assign sel_tmp2_fu_1285_p2 = ((m_fu_1256_p1 == 2'd3) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_1327_p2 = ((m_fu_1256_p1 == 2'd0) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_1299_p2 = ((m_fu_1256_p1 == 2'd2) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_973_p2 = (tmp_61_fu_951_p3 ^ 1'd1);

assign sel_tmp6_fu_979_p2 = (tmp_38_fu_963_p2 & sel_tmp5_fu_973_p2);

assign sel_tmp7_fu_1181_p2 = (tmp4_fu_1175_p2 & tmp3_fu_1169_p2);

assign sel_tmp8_fu_1313_p2 = ((m_fu_1256_p1 == 2'd1) ? 1'b1 : 1'b0);

assign sel_tmp_fu_872_p2 = (tmp_35_fu_850_p3 ^ 1'd1);

assign tile_valid = sel_tmp7_reg_1725_pp0_iter10_reg;

assign tmp1_fu_379_p2 = ($signed(9'd511) + $signed(tmp_cast_fu_376_p1));

assign tmp21_cast_fu_385_p1 = $signed(tmp1_fu_379_p2);

assign tmp22_cast_fu_403_p1 = $signed(tmp2_fu_397_p2);

assign tmp2_fu_397_p2 = ($signed(9'd511) + $signed(tmp_5_cast_fu_394_p1));

assign tmp3_fu_1169_p2 = (tmp_50_fu_1116_p2 & tmp_48_fu_1100_p2);

assign tmp4_fu_1175_p2 = (tmp_55_fu_1163_p2 & tmp_53_fu_1147_p2);

assign tmp_10_fu_446_p1 = $signed(M3_read_reg_1369_pp0_iter1_reg);

assign tmp_11_fu_449_p1 = $signed(M4_read_reg_1364_pp0_iter1_reg);

assign tmp_12_fu_515_p1 = $signed(M5_read_reg_1359_pp0_iter6_reg);

assign tmp_13_fu_348_p1 = s_w;

assign tmp_14_fu_358_p1 = s_h;

assign tmp_15_fu_418_p2 = ($signed(cd00_reg_1416) - $signed(tmp_4_fu_412_p1));

assign tmp_16_cast2_fu_823_p1 = s_w_read_reg_1396_pp0_iter8_reg;

assign tmp_16_cast3_fu_826_p1 = s_w_read_reg_1396_pp0_iter8_reg;

assign tmp_16_cast_fu_829_p1 = s_w_read_reg_1396_pp0_iter8_reg;

assign tmp_16_fu_423_p2 = ($signed(rd00_reg_1424) - $signed(tmp_s_fu_415_p1));

assign tmp_17_cast_fu_518_p1 = $signed(tmp_13_reg_1440_pp0_iter6_reg);

assign tmp_17_fu_452_p1 = $signed(tmp_15_reg_1468);

assign tmp_19_cast1_fu_832_p1 = s_h_read_reg_1389_pp0_iter8_reg;

assign tmp_19_cast2_fu_835_p1 = s_h_read_reg_1389_pp0_iter8_reg;

assign tmp_19_cast_fu_838_p1 = s_h_read_reg_1389_pp0_iter8_reg;

assign tmp_19_fu_461_p1 = $signed(tmp_16_reg_1473);

assign tmp_20_cast_fu_521_p1 = $signed(tmp_14_reg_1445_pp0_iter6_reg);

assign tmp_21_fu_524_p2 = ($signed(tmp_18_reg_1536) + $signed(tmp_9_fu_512_p1));

assign tmp_22_fu_529_p2 = (tmp_21_fu_524_p2 + tmp_20_reg_1541);

assign tmp_24_cast_fu_858_p1 = $unsigned(min2_1_cast_fu_846_p1);

assign tmp_25_fu_534_p2 = ($signed(tmp_23_reg_1547) + $signed(tmp_12_fu_515_p1));

assign tmp_26_1_fu_428_p2 = ($signed(cd11_fu_389_p2) - $signed(tmp_4_fu_412_p1));

assign tmp_26_fu_539_p2 = (tmp_25_fu_534_p2 + tmp_24_reg_1552);

assign tmp_27_2_fu_434_p2 = ($signed(rd11_fu_407_p2) - $signed(tmp_s_fu_415_p1));

assign tmp_27_fu_544_p4 = {{tmp_22_fu_529_p2[31:15]}};

assign tmp_28_1_fu_482_p1 = $signed(tmp_26_1_reg_1478);

assign tmp_28_fu_558_p4 = {{tmp_26_fu_539_p2[31:15]}};

assign tmp_29_fu_604_p4 = {{tmp_33_1_fu_589_p2[31:15]}};

assign tmp_2_fu_443_p1 = $signed(M1_read_reg_1379_pp0_iter1_reg);

assign tmp_30_2_fu_497_p1 = $signed(tmp_27_2_reg_1483);

assign tmp_30_fu_618_p4 = {{tmp_38_1_fu_599_p2[31:15]}};

assign tmp_31_fu_654_p4 = {{tmp_33_2_fu_644_p2[31:15]}};

assign tmp_32_1_fu_584_p2 = ($signed(tmp_29_1_reg_1558) + $signed(tmp_9_fu_512_p1));

assign tmp_32_fu_668_p4 = {{tmp_38_2_fu_649_p2[31:15]}};

assign tmp_33_1_fu_589_p2 = (tmp_32_1_fu_584_p2 + tmp_20_reg_1541);

assign tmp_33_2_fu_644_p2 = (tmp_21_fu_524_p2 + tmp_31_2_reg_1568);

assign tmp_33_3_fu_694_p2 = (tmp_32_1_fu_584_p2 + tmp_31_2_reg_1568);

assign tmp_33_fu_704_p4 = {{tmp_33_3_fu_694_p2[31:15]}};

assign tmp_34_fu_718_p4 = {{tmp_38_3_fu_699_p2[31:15]}};

assign tmp_35_fu_850_p3 = min2_1_fu_841_p3[32'd17];

assign tmp_36_fu_862_p2 = (($signed(tmp_24_cast_fu_858_p1) > $signed(tmp_16_cast_fu_829_p1)) ? 1'b1 : 1'b0);

assign tmp_37_1_fu_594_p2 = ($signed(tmp_35_1_reg_1563) + $signed(tmp_12_fu_515_p1));

assign tmp_37_fu_909_p2 = (($signed(max1_1_fu_903_p3) > $signed(tmp_16_cast3_fu_826_p1)) ? 1'b1 : 1'b0);

assign tmp_38_1_fu_599_p2 = (tmp_37_1_fu_594_p2 + tmp_24_reg_1552);

assign tmp_38_2_fu_649_p2 = (tmp_25_fu_534_p2 + tmp_36_2_reg_1574);

assign tmp_38_3_fu_699_p2 = (tmp_37_1_fu_594_p2 + tmp_36_2_reg_1574);

assign tmp_38_fu_963_p2 = (($signed(tmp_57_cast_fu_959_p1) > $signed(tmp_19_cast_fu_838_p1)) ? 1'b1 : 1'b0);

assign tmp_39_fu_1010_p2 = (($signed(max1_3_fu_1004_p3) > $signed(tmp_19_cast2_fu_835_p1)) ? 1'b1 : 1'b0);

assign tmp_40_cast_fu_554_p1 = $signed(tmp_27_fu_544_p4);

assign tmp_40_fu_1055_p2 = ($signed(tmp_66_cast_fu_1047_p1) - $signed(tmp_68_cast_fu_1051_p1));

assign tmp_41_fu_1192_p2 = (13'd0 - tmp_40_reg_1711_pp0_iter10_reg);

assign tmp_42_fu_915_p3 = max1_1_fu_903_p3[32'd17];

assign tmp_43_cast_fu_568_p1 = $signed(tmp_28_fu_558_p4);

assign tmp_43_fu_1069_p2 = ($signed(tmp_70_cast_fu_1061_p1) - $signed(tmp_71_cast_fu_1065_p1));

assign tmp_44_fu_1221_p2 = (13'd0 - tmp_43_reg_1718_pp0_iter10_reg);

assign tmp_45_fu_1237_p2 = (($signed(s_tile_h_fu_1197_p3) < $signed(13'd1)) ? 1'b1 : 1'b0);

assign tmp_46_cast_fu_614_p1 = $signed(tmp_29_fu_604_p4);

assign tmp_46_fu_1075_p3 = {{w_div_read_reg_1410_pp0_iter8_reg}, {3'd0}};

assign tmp_47_fu_1090_p2 = ($signed(tmp_78_cast1_fu_1082_p1) + $signed(tmp_16_cast2_fu_823_p1));

assign tmp_48_fu_1100_p2 = (($signed(min2_1_fu_841_p3) < $signed(tmp_79_cast_fu_1096_p1)) ? 1'b1 : 1'b0);

assign tmp_49_fu_1106_p2 = ($signed(12'd0) - $signed(tmp_78_cast_fu_1086_p1));

assign tmp_4_fu_412_p1 = $signed(tmp_7_reg_1430);

assign tmp_50_fu_1116_p2 = (($signed(max1_1_fu_903_p3) > $signed(tmp_81_cast_fu_1112_p1)) ? 1'b1 : 1'b0);

assign tmp_51_fu_1122_p3 = {{h_div_read_reg_1404_pp0_iter8_reg}, {3'd0}};

assign tmp_52_fu_1137_p2 = ($signed(12'd0) - $signed(tmp_88_cast_fu_1133_p1));

assign tmp_53_cast_fu_628_p1 = $signed(tmp_30_fu_618_p4);

assign tmp_53_fu_1147_p2 = (($signed(max1_3_fu_1004_p3) > $signed(tmp_89_cast_fu_1143_p1)) ? 1'b1 : 1'b0);

assign tmp_54_fu_1153_p2 = ($signed(tmp_88_cast1_fu_1129_p1) + $signed(tmp_19_cast1_fu_832_p1));

assign tmp_55_fu_1163_p2 = (($signed(min2_3_fu_942_p3) < $signed(tmp_93_cast_fu_1159_p1)) ? 1'b1 : 1'b0);

assign tmp_57_cast_fu_959_p1 = $unsigned(min2_3_cast_fu_947_p1);

assign tmp_58_cast_fu_664_p1 = $signed(tmp_31_fu_654_p4);

assign tmp_5_cast_fu_394_p1 = h_div_read_reg_1404;

assign tmp_5_fu_314_p0 = h_div;

assign tmp_61_fu_951_p3 = min2_3_fu_942_p3[32'd17];

assign tmp_64_fu_1016_p3 = max1_3_fu_1004_p3[32'd17];

assign tmp_65_cast_fu_678_p1 = $signed(tmp_32_fu_668_p4);

assign tmp_66_cast_fu_1047_p1 = rt_1_fu_992_p3;

assign tmp_66_fu_1209_p1 = s_tile_h_fu_1197_p3[11:0];

assign tmp_68_cast_fu_1051_p1 = $signed(rb_1_fu_1036_p3);

assign tmp_70_cast_fu_1061_p1 = cl_1_fu_891_p3;

assign tmp_71_cast_fu_1065_p1 = $signed(cr_1_fu_935_p3);

assign tmp_76_cast_fu_714_p1 = $signed(tmp_33_fu_704_p4);

assign tmp_78_cast1_fu_1082_p1 = tmp_46_fu_1075_p3;

assign tmp_78_cast_fu_1086_p1 = tmp_46_fu_1075_p3;

assign tmp_79_cast_fu_1096_p1 = $signed(tmp_47_fu_1090_p2);

assign tmp_81_cast_fu_1112_p1 = $signed(tmp_49_fu_1106_p2);

assign tmp_86_cast_fu_728_p1 = $signed(tmp_34_fu_718_p4);

assign tmp_88_cast1_fu_1129_p1 = tmp_51_fu_1122_p3;

assign tmp_88_cast_fu_1133_p1 = tmp_51_fu_1122_p3;

assign tmp_89_cast_fu_1143_p1 = $signed(tmp_52_fu_1137_p2);

assign tmp_8_fu_440_p1 = $signed(M0_read_reg_1384_pp0_iter1_reg);

assign tmp_93_cast_fu_1159_p1 = $signed(tmp_54_fu_1153_p2);

assign tmp_97_i1_fu_802_p2 = (($signed(min1_1_fu_786_p3) > $signed(min2_2_fu_796_p3)) ? 1'b1 : 1'b0);

assign tmp_97_i_fu_764_p2 = (($signed(min1_fu_748_p3) > $signed(min2_fu_758_p3)) ? 1'b1 : 1'b0);

assign tmp_98_i1_fu_1000_p2 = (($signed(max1_2_reg_1678) > $signed(max2_1_reg_1684)) ? 1'b1 : 1'b0);

assign tmp_98_i_fu_899_p2 = (($signed(max1_reg_1651) > $signed(max2_reg_1657)) ? 1'b1 : 1'b0);

assign tmp_9_fu_512_p1 = $signed(M2_read_reg_1374_pp0_iter6_reg);

assign tmp_cast_fu_376_p1 = w_div_read_reg_1410;

assign tmp_fu_300_p0 = w_div;

assign tmp_i1_7_fu_792_p2 = (($signed(rs_2_reg_1615) > $signed(rs_3_reg_1629)) ? 1'b1 : 1'b0);

assign tmp_i1_fu_782_p2 = (($signed(rs_0_reg_1587) > $signed(rs_1_reg_1601)) ? 1'b1 : 1'b0);

assign tmp_i_6_fu_754_p2 = (($signed(cs_2_reg_1608) > $signed(cs_3_reg_1622)) ? 1'b1 : 1'b0);

assign tmp_i_fu_744_p2 = (($signed(cs_0_reg_1580) > $signed(cs_1_reg_1594)) ? 1'b1 : 1'b0);

assign tmp_s_fu_415_p1 = $signed(tmp_3_reg_1435);

assign top_row = rt_1_reg_1701_pp0_iter10_reg;

assign ws = $signed(s_tile_w_r2_8_fu_1333_p3);

endmodule //tdt
